### ISSUE TITLE
Can @ingredients be augmented to accept module files?/ @ingredients does not play nice with module files

### ISSUE THREAD

**Issue by unnamedunknownusername** [JuliaPluto/PlutoLinks.jl#14]
Hi there

So I like to write out/develop and keep my functions in Pluto notebooks
e.g. I have `notebook1.jl`
```.jl
function MyFunc(a,b,c)
 a+b-c
end
```

and `notebook2.jl`
```.jl
function MyFunc2(a)
 a
end
```

(the functions don't exactly matter)

Because Pluto notebooks are just plain julia files(which I love), I then compose my notebooks together in module files (that are not notebooks, though I guess they could be)
i.e. I have a file named `functionsmodule.jl`
```.jl
module functionsmodule

include("notebook1.jl")
include("notebook1.jl")

end
```

I then use those modules in other notebooks. It is easier for me to import a group of functions together instead of having to call ingredients on each separate notebook - it also helps seperate and group similar/related code together)
![image](https://github.com/JuliaPluto/PlutoLinks.jl/assets/109242984/d4237719-442e-4283-9e17-ba5825b45105)
As shown above this works but the module is wrapped in another module which here i have labeled `x` so in order to get to my functions I have to go `x.functionsmodule.MyFunc()`. 

I have found a work around:
If I comment out the module and end key words in `functionsmodule.jl` 
```.jl
#module functionsmodule

include("notebook1.jl")
include("notebook1.jl")

#end
```
then I can name the variable `functionsmodule` instead of `x` and get the desired result
![image](https://github.com/JuliaPluto/PlutoLinks.jl/assets/109242984/e89f802d-6f87-499f-a637-b7dc453d33a3)
but then I don't "really" have a `module` in the `functionsmodule.jl` file which I would ideally want.

It would be really nice if I didn't have to comment out the module and end keywords (that way I could make nice packages if need be) and if ingredients was able to handle `module` files/files with `module` at the top
![image](https://github.com/JuliaPluto/PlutoLinks.jl/assets/109242984/773b4b48-da55-46e7-8f9c-aae527a83ee6)

I am thinking we could do something before the module was returned, not sure if you can force the returned module to have a specific name linked to the filename input (I do not think it would be that bad if I still had to name the variable it would then function similar to `import XYZ as xyz`)
```.jl
function ingredients(path::String)
# this is from the Julia source code (evalfile in base/loading.jl)
# but with the modification that it returns the module instead of the last object
name = Symbol(basename(path))

m = Module(name)

#Do something here like comment out/strip module from module files or something like that to allow them to work as described

Core.eval(m,
Expr(:toplevel,
:(eval(x) = $(Expr(:core, :eval))($name, x)),
:(include(x) = $(Expr(:top, :include))($name, x)),
:(include(mapexpr::Function, x) = $(Expr(:top, :include))(mapexpr, $name, x)),
:(include($path))
)
)
m

end
```

or do something before it gets to the function?
```.jl
macro ingredients(filename)
	quote
		let
			filename = $(esc(filename))

#Do something here like comment out/strip module from module files or something like that to allow them to work as described

			update_time = @use_file_change(filename)
			@use_memo([update_time]) do
				ingredients(filename)
			end
		end
	end
end
```

I tried fiddling around with these functions but I am a novice when it comes to meta programming - so I didn't really get anywhere

I'd be happy to create/contribute to a PR if I got some guidance 

Many thanks in advance

**Comment by Pangoraw** [comment]
Thanks for the detailed explanation of your problem!

In your case, you should be able to do:

```julia
myfunctions = @ingredients("path_to_file.jl").myfunctions
# or if julia>=1.8
(; myfunctions) = @ingredients("path_to_file.jl")
```
and then you should be able to call

```julia
myfunctions.MyFunc()
```

Having a different behavior when the file is a module feels a bit weird to me because it is less consistent.

**Comment by unnamedunknownusername** [comment]
Oh of course, I can reference the module at the site of invoking/calling `@ingredients`. That was silly of me to forget. Thanks so much.

>Having a different behavior when the file is a module feels a bit weird to me because it is less consistent.

That's fair. Yeah my whole current process is sort of a work around, I am waiting for the notebook-in-notebooks features that have sometimes been spoken about. But I know that the dependency problem/managing the dependencies is tricky there.

I will close this as resolved as it works for my use case
Thanks for your help again.
